# Generated by Django 4.1.7 on 2023-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_upload_project_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_project',
            old_name='description',
            new_name='pdesc',
        ),
        migrations.RenameField(
            model_name='upload_project',
            old_name='name',
            new_name='pname',
        ),
        migrations.AlterField(
            model_name='upload_project',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
